# Generated by Django 2.2.2 on 2024-06-10 12:53

import Q_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.BinaryField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=Q_app.models.upload_path)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='logindetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('sel_options', models.CharField(max_length=100)),
                ('selected_col', models.CharField(max_length=100)),
                ('client_access', models.CharField(max_length=200)),
                ('planned_impressions', models.CharField(max_length=100)),
                ('planned_cpm', models.CharField(max_length=100)),
                ('planned_clicks', models.CharField(max_length=100)),
                ('planned_cpc', models.CharField(max_length=100)),
                ('planned_session', models.CharField(max_length=100)),
                ('planned_cps', models.CharField(max_length=100)),
                ('planned_budget_impressions', models.CharField(max_length=100)),
                ('planned_budget_clicks', models.CharField(max_length=100)),
                ('planned_budget_sessions', models.CharField(max_length=100)),
                ('ctr', models.CharField(max_length=10)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q_app.clientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='user_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('no_of_impressions', models.IntegerField()),
                ('no_of_clicks', models.IntegerField()),
                ('no_of_sessions', models.IntegerField()),
                ('cpm', models.FloatField()),
                ('cpc', models.FloatField()),
                ('cost_per_session', models.FloatField()),
                ('total_cpm', models.FloatField()),
                ('total_cpc', models.FloatField()),
                ('total_cps', models.FloatField()),
                ('ctr', models.FloatField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q_app.requirements')),
            ],
        ),
    ]
